language: cpp
compiler:
  - gcc
  - clang

env:
  global:
    - FC=gfortran
    - CC=gcc-4.9
    - CXX=g++-4.9

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y cmake gfortran
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi

script: cd bem && ./build.sh

# whitelist
branches:
  only:
    - cmake_builds
