language: cpp
compiler:
  - gcc
  - clang

env:
  global:
    - FC=gfortran
    - CXX=gcc-4.8

before_install:
  - sudo apt-get update -qq
  - sudo apt-get upgrade gcc
  - sudo apt-get install -y cmake gfortran


script: cd bem && ./build.sh

# whitelist
branches:
  only:
    - cmake_builds
