language: cpp
compiler:
  - gcc
  - clang

env:
  global:
    - FC=gfortran

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install cmake gfortran


script: cd bem && ./build.sh

# whitelist
branches:
  only:
    - cmake_builds
